#!/bin/bash
dot="$(cd "$(dirname "$0")"; pwd)"
path="s|PATH|$dot|g"

echo "Creating a database tpch, the necessary tables and importing the data";
echo  "This will take a few minutes, please wait";

sed -i $path tpch_to_mariadb_with_view.sql

sudo mysql -u ${1?The script should be executed as follows: ./import_TPCH_to_MariaDB.sh <DB Username>} -p  < tpch_to_mariadb_with_view.sql

echo "Reaching end of Script, Please visit the ./queries folder for sample queries generated by TPC-H to benchmark your database."
echo "A sample MySQL/MariaDB exist on Github dhuny/tpch. You may use it as an example to adapt your sample queries generated by TPCH. "
echo "Do compare your output results with the expected output present in TPC-H documentation."